# Number of days of inactivity before an issue becomes stale
daysUntilStale: 10
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 5
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - investigating
  - bug report
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had recent activity. 
  It will be closed if no further activity occurs.
  
  Questions are community supported only and the authors/maintainers may or may not have time to reply. If you or your company would like commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
