//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer4.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Events() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer4.Core.Resources.Events", typeof(Events).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Client Permissions Revoked.
        /// </summary>
        internal static string ClientPermissionsRevoked {
            get {
                return ResourceManager.GetString("ClientPermissionsRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Content Security Policy (CSP) Report.
        /// </summary>
        internal static string CspReport {
            get {
                return ResourceManager.GetString("CspReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to External Login Error.
        /// </summary>
        internal static string ExternalLoginError {
            get {
                return ResourceManager.GetString("ExternalLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to External Login Failure.
        /// </summary>
        internal static string ExternalLoginFailure {
            get {
                return ResourceManager.GetString("ExternalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to External Login Success.
        /// </summary>
        internal static string ExternalLoginSuccess {
            get {
                return ResourceManager.GetString("ExternalLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Local Login Failure.
        /// </summary>
        internal static string LocalLoginFailure {
            get {
                return ResourceManager.GetString("LocalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Local Login Success.
        /// </summary>
        internal static string LocalLoginSuccess {
            get {
                return ResourceManager.GetString("LocalLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Logout Event.
        /// </summary>
        internal static string LogoutEvent {
            get {
                return ResourceManager.GetString("LogoutEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Partial Login.
        /// </summary>
        internal static string PartialLogin {
            get {
                return ResourceManager.GetString("PartialLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Partial Login Complete.
        /// </summary>
        internal static string PartialLoginComplete {
            get {
                return ResourceManager.GetString("PartialLoginComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pre-Login Failure.
        /// </summary>
        internal static string PreLoginFailure {
            get {
                return ResourceManager.GetString("PreLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pre-Login Success.
        /// </summary>
        internal static string PreLoginSuccess {
            get {
                return ResourceManager.GetString("PreLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Resource Owner Password Flow Login Failure.
        /// </summary>
        internal static string ResourceOwnerFlowLoginFailure {
            get {
                return ResourceManager.GetString("ResourceOwnerFlowLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Resource Owner Password Flow Login Success.
        /// </summary>
        internal static string ResourceOwnerFlowLoginSuccess {
            get {
                return ResourceManager.GetString("ResourceOwnerFlowLoginSuccess", resourceCulture);
            }
        }
    }
}
