//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer4.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scopes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Scopes() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer4.Core.Resources.Scopes", typeof(Scopes).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your postal address.
        /// </summary>
        internal static string address_DisplayName {
            get {
                return ResourceManager.GetString("address_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to All user information.
        /// </summary>
        internal static string all_claims_DisplayName {
            get {
                return ResourceManager.GetString("all_claims_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your email address.
        /// </summary>
        internal static string email_DisplayName {
            get {
                return ResourceManager.GetString("email_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Offline access.
        /// </summary>
        internal static string offline_access_DisplayName {
            get {
                return ResourceManager.GetString("offline_access_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your user identifier.
        /// </summary>
        internal static string openid_DisplayName {
            get {
                return ResourceManager.GetString("openid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your phone number.
        /// </summary>
        internal static string phone_DisplayName {
            get {
                return ResourceManager.GetString("phone_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your user profile information (first name, last name, etc.).
        /// </summary>
        internal static string profile_Description {
            get {
                return ResourceManager.GetString("profile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User profile.
        /// </summary>
        internal static string profile_DisplayName {
            get {
                return ResourceManager.GetString("profile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User roles.
        /// </summary>
        internal static string roles_DisplayName {
            get {
                return ResourceManager.GetString("roles_DisplayName", resourceCulture);
            }
        }
    }
}
